// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.

namespace Microsoft.Azure.Management.Monitor.Fluent.Models
{
    using Microsoft.Azure.Management.ResourceManager.Fluent.Core;

    /// <summary>
    /// Defines values for MetricAlertRuleCondition.
    /// </summary>
    public sealed partial class MetricAlertRuleCondition : ExpandableStringEnum<MetricAlertRuleCondition>
    {
        public static readonly MetricAlertRuleCondition IsEqual = Parse("Equals");
        public static readonly MetricAlertRuleCondition NotEquals = Parse("NotEquals");
        public static readonly MetricAlertRuleCondition GreaterThan = Parse("GreaterThan");
        public static readonly MetricAlertRuleCondition GreaterThanOrEqual = Parse("GreaterThanOrEqual");
        public static readonly MetricAlertRuleCondition LessThan = Parse("LessThan");
        public static readonly MetricAlertRuleCondition LessThanOrEqual = Parse("LessThanOrEqual");
    }
}
