// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// </auto-generated>

using System.Reflection;
using System.Resources;

[assembly: AssemblyTitle("Microsoft Azure BatchAI Management Library")]
[assembly: AssemblyDescription("Provides Microsoft Azure BatchAI management APIs.")]

[assembly: AssemblyVersion("1.0.0.60")]
[assembly: AssemblyFileVersion("1.16.1.0")]

[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Azure .NET SDK")]
[assembly: AssemblyCopyright("Copyright (c) Microsoft Corporation")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en")]
