// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// </auto-generated>

namespace Microsoft.Azure.Management.ContainerInstance.Fluent.Models
{
    using Microsoft.Azure.Management.ResourceManager.Fluent.Core;

    /// <summary>
    /// Defines values for ContainerGroupRestartPolicy.
    /// </summary>
    public class ContainerGroupRestartPolicy : ExpandableStringEnum<ContainerGroupRestartPolicy>
    {
        public static readonly ContainerGroupRestartPolicy Always = Parse("Always");
        public static readonly ContainerGroupRestartPolicy OnFailure = Parse("OnFailure");
        public static readonly ContainerGroupRestartPolicy Never = Parse("Never");
    }
}
